name: Build Flappy Bird APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      # Step 3: Install system dependencies
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-dev \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            zlib1g-dev \
            libffi-dev \
            libssl-dev \
            autoconf \
            libtool \
            pkg-config \
            cmake \
            libncurses5-dev \
            libncursesw5-dev

      # Step 4: Install Buildozer and dependencies
      - name: Install Buildozer and dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade Cython==0.29.33 buildozer

      # Step 5: Download and configure Android NDK
      - name: Download and set up Android NDK r23b
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r23b-linux.zip
          unzip android-ndk-r23b-linux.zip -d $HOME
          echo "ANDROID_NDK=$HOME/android-ndk-r23b" >> $GITHUB_ENV

      # Step 6: Clean previous builds
      - name: Clean Buildozer cache
        run: buildozer android clean

      # Step 7: Build the APK
      - name: Build APK with Buildozer
        run: buildozer android debug
