name: Build APK for flappybird 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    # Install dependencies
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git python3-dev build-essential

    # Download Android SDK Command Line Tools
    - name: Download Android SDK Command Line Tools
      run: |
        mkdir -p /home/runner/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O commandlinetools.zip
        unzip -o commandlinetools.zip -d /home/runner/android-sdk/cmdline-tools
        rm commandlinetools.zip
        mkdir -p /home/runner/android-sdk/cmdline-tools/latest
        mv /home/runner/android-sdk/cmdline-tools/cmdline-tools/* /home/runner/android-sdk/cmdline-tools/latest
        mkdir -p /home/runner/android-sdk/tools/bin
        ln -sf /home/runner/android-sdk/cmdline-tools/latest/bin/sdkmanager /home/runner/android-sdk/tools/bin/sdkmanager
        echo "sdkmanager path: /home/runner/android-sdk/tools/bin/sdkmanager"
      
    # Accept Android SDK Licenses
    - name: Accept Android SDK Licenses
      run: |
        yes | /home/runner/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

    # Install Android SDK components
    - name: Install SDK Components
      run: |
        /home/runner/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

    # Install NDK (Optional)
    - name: Install NDK
      run: |
        /home/runner/android-sdk/cmdline-tools/latest/bin/sdkmanager "ndk;25.2.9519653"

    # Set up environment variables for Buildozer
    - name: Set up environment variables
      run: |
        echo "ANDROID_HOME=/home/runner/android-sdk" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=/home/runner/android-sdk" >> $GITHUB_ENV

    # Install Buildozer and clean build
    - name: Install Buildozer and Clean Build
      run: |
        pip install buildozer
        buildozer android clean

    # Build the APK
    - name: Build APK
      run: |
        buildozer -v android debug

    # Upload APK to GitHub Releases
    - name: Upload APK to GitHub Releases
      if: success()
      uses: ncipollo/release-action@v1
      with:
        artifacts: 'bin/*.apk'
