
on:
 push:
  branches: [main]

jobs:
 build:
  runs-on: ubuntu-22.04
  steps:
  - uses: actions/checkout@v4

  - name: Install Android SDK command-line tools
    run: |
      sudo apt-get update
      sudo apt-get install -y wget unzip
      wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O cmdline-tools.zip
      mkdir -p /usr/local/lib/android/sdk/cmdline-tools
      unzip cmdline-tools.zip -d /usr/local/lib/android/sdk/cmdline-tools
      mv /usr/local/lib/android/sdk/cmdline-tools/cmdline-tools /usr/local/lib/android/sdk/cmdline-tools/latest

  - name: Set up Android SDK
    run: |
      echo "ANDROID_SDK_ROOT=/usr/local/lib/android/sdk" >> $GITHUB_ENV
      yes | /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --install "build-tools;30.0.3" "platforms;android-30"

  - name: Install dependencies
    run: |
           sudo apt-get update
           sudo apt-get install -y \
            libpython3-dev \
            python3-dev \
            build-essential \
            libncurses5-dev \
            libncursesw5-dev \
            libreadline-dev \
            libssl-dev \
            libffi-dev \
            zlib1g-dev \
            libbz2-dev \
            libsqlite3-dev \
            wget \
            curl \
            git \
            python3-pip
           pip3 install pygame
   
  - name: Build APK
    uses: digreatbrian/buildozer-action@v2
    with:
     python-version: 3.9
     buildozer-cmd: buildozer -v android debug

  - name: Upload artifacts
    uses: actions/upload-artifact@v4
    with:
     name: package
     path: ./bin/*.apk
