name: Build Flappy Bird APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip openjdk-17-jdk python3-setuptools python3-wheel git unzip
          pip install --upgrade pip
          pip install buildozer
          pip install cython

      - name: Set up Android SDK
        run: |
          mkdir -p ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest
          cd ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O commandlinetools.zip
          unzip commandlinetools.zip
          rm commandlinetools.zip
          export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
          export PATH=$ANDROID_SDK_ROOT/platform-tools:$PATH
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0"

      - name: Build APK
        run: |
          cd $GITHUB_WORKSPACE
          buildozer android debug
          mkdir -p $GITHUB_WORKSPACE/apk
          cp bin/*.apk $GITHUB_WORKSPACE/apk

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: FlappyBird-APK
          path: apk/
