on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-dev \
          build-essential \
          libpython3-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libreadline-dev \
          libssl-dev \
          libffi-dev \
          zlib1g-dev \
          libbz2-dev \
          libsqlite3-dev \
          wget \
          curl \
          git \
          python3-pip

    - name: Install Python dependencies
      run: |
        pip3 install --upgrade pip
        pip3 install buildozer cython pygame

    - name: Set environment variables
      run: |
        echo "ANDROIDSDK=/root/android-sdk" >> $GITHUB_ENV
        echo "ANDROIDNDK=/root/android-sdk/ndk/android-ndk-r25.2.9519653" >> $GITHUB_ENV
        echo "ANDROIDAPI=33" >> $GITHUB_ENV
        echo "ANDROIDMINAPI=21" >> $GITHUB_ENV

    - name: Build APK
      uses: digreatbrian/buildozer-action@v2
      with:
        python-version: 3.9
        buildozer-version: 1.4.0
        buildozer-cmd: android debug

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: flappybird-debug-apk
        path: ./bin/*.apk
