name: Build Flappy Bird APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Buildozer
      run: |
        sudo apt update
        sudo apt install -y python3-pip openjdk-17-jdk python3-setuptools python3-wheel git unzip
        pip install --upgrade pip
        pip install buildozer

    - name: Build APK
      run: |
        buildozer android debug
        mkdir -p $GITHUB_WORKSPACE/apk
        cp bin/*.apk $GITHUB_WORKSPACE/apk

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: FlappyBird-APK
        path: apk/