name: Build Flappy Bird APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            python3-pip \
            openjdk-17-jdk \
            python3-setuptools \
            python3-wheel \
            git \
            unzip

          pip install --upgrade pip
          pip install cython buildozer pygame pandas numpy scipy pillow

      - name: Download and Set Up Android Command-Line Tools
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
          unzip -o cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager \
            "platform-tools" \
            "platforms;android-31" \
            "build-tools;31.0.0" \
            "system-images;android-31;default;x86_64" \
            "cmdline-tools;latest" \
            "emulator"

      - name: Build APK
        run: |
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH
          buildozer android debug
          mkdir -p $GITHUB_WORKSPACE/apk
          cp bin/*.apk $GITHUB_WORKSPACE/apk

      - name: Upload APK  
        uses: actions/upload-artifact@v3
        with:
          name: FlappyBird-APK
          path: apk/
