name: Build Flappy Bird APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            python3-pip \
            openjdk-17-jdk \
            python3-setuptools \
            python3-wheel \
            git \
            unzip \
            android-sdk \
            android-ndk \
            gradle \
            maven \
            android-studio

          pip install --upgrade pip
          pip install cython
          pip install buildozer
          pip install pygame
          pip install pandas
          pip install numpy
          pip install scipy
          pip install pillow

      - name: Set up Android SDK
        run: |
          echo "sdkman_auto_answer=true" >> ~/.sdkman/etc/config
          sdkman install java 17.0.2-open
          sdkman install android-sdk 4333796
          sdkman install android-ndk 23.1.7779620

      - name: Build APK
        run: |
          buildozer init
          buildozer android debug
          mkdir -p $GITHUB_WORKSPACE/apk
          cp bin/*.apk $GITHUB_WORKSPACE/apk

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: FlappyBird-APK
          path: apk/
