on:
 push:
  branches: [main]

jobs:
 build:
  runs-on: ubuntu-22.04
  steps:
  - uses: actions/checkout@v4
  - name: Install dependencies
    run: |
           sudo apt-get update
           sudo apt-get install -y \
            libpython3-dev \
            python3-dev \
            build-essential \
            libncurses5-dev \
            libncursesw5-dev \
            libreadline-dev \
            libssl-dev \
            libffi-dev \
            zlib1g-dev \
            libbz2-dev \
            libsqlite3-dev \
            wget \
            curl \
            git
  - name: Build APK
    uses: digreatbrian/buildozer-action@v2
    with:
     python-version: 3.8
     buildozer-cmd: buildozer -v android debug

  - name: Upload artifacts
    uses: actions/upload-artifact@v4
    with:
     name: package
     path: ./bin/*.apk
  
